name: build_ErfanGSIs

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    
env:
  ROM_URL: https://doc-0s-b4-docs.googleusercontent.com/docs/securesc/obgnrk9dkgrrh6v136t6400lkvjc500l/6n97f5mdasa63er8tis0m5p1gohtc17f/1667521200000/16181688176757446243/04468167983942270696/166hF2xBHA-0R5UeAFovJRX6FkXsEt5XQ?e=download&ax=ALW9-sBAnOQ6RAEF0cwXUKXKpSA-ES-7-moqTijOf7aCvD7GlwO4og6odVMJl0376rALviGKwrBPue7ZXRY44zHltYTGVM74dIV5ZI89AeDJYwQa3qJ6I0XueR6WwW15xs2vXFH164y2-zA4IajZq5Q1XEsIiUXsxsVLdynvN2ZcskGGdTBEvFrMQw7zZcLpjs3FP96txMof5GZiSNwnKvBnaxgtm1tJzGB8dHXZ0sLlhrtLo-qzaJNXwBX2qXLFRi2C65qd2J-4iys3YZ2a5otzUH2jb-U6zllPftIbe30STIhTngB1qFLOOfZe9C9GRBOkUAwYdL4bQj8NzESCTcATIAsZ_4wrik-61pNe1mRXrblpItJjEiuzIAFTuihFNg0xJGh3evz7lj52LoYGb2e8rZLFU_K6kRjWu95LTLSC0GJQyaQuZQlMHWD-U0YR7faRSHDr6nMOrDLyuWy_jFhqndoKHJV2vOhSjoBRn2B7vj1CsIXG2fOZrpQTRCj7OwFPmxKJO38ppafykKE7RDuNxW29Q12OT0AQx6HIo-_N3Q8ipxtdXwoGrq4rt2rrYQfMmBv-Iv6zvJ5YrlVHeVJCoRSqwYkff70NJr3NvMwP18RDBWYl2VqWsiGQ_h29IVj0nGwbRMV165JO4N6AIPBpp58KDnnNwtMe2vELpC4XD00F7kda4qmulpTwNhPZM20mBTrQlj0S-h_6ONvvh1iCQ_lTadU0hx9YUFRxku6XlXNIFq4w98nfh6NNZaRz2sr5qhU8nAhLoZy7Pm7D0TrO1R8PA5j_g_TqXoI9-XKKZK2SrZu8-1M68usCOQvXQ07JRnLxGDRxF33SWSMzQzsXRikpPw77KakbScB6VmLH7JP2X1pjL-85T213OxablCpKN0419K-wgw6HTsBbj8wJngm0weHLqmdTIVEhJ4aO1nxEpUivzbGRET6lc-YmwGkmKyVVP0LVHR81l55c3A1WsfrdWoe2vNuUT3078sw88dM&uuid=6066e536-303f-4e43-be75-496bd9a10593&authuser=0&nonce=10iala819an9c&user=04468167983942270696&hash=irfapm8n5sopsb61gmjbr9oq82eh68eo
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ~/ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' ~/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' ~/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd ~/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd ~/ErfanGSIs 
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd ~/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd ~/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
